# -*- coding: utf-8 -*-
"""Batch5: long tutorial/warning/settings texts (user-visible)."""
import json, os

S = "\ue001"

B = {
    "The process cannot access the file because another process has locked": "进程无法访问该文件，因为另一个进程已将其锁定",
    "The wallet file is locked. Is another instance of Sparrow already running?": "钱包文件已被锁定。是否已有另一个 Sparrow 实例正在运行？",
    "The card was successfully initialized.\n\nYou can now import the keystore.": "卡片已成功初始化。\n\n你现在可以导入密钥库。",
    "Export does not contain the spscan value for silent payments": "导出不包含静默支付的 spscan 值",
    "A Tor proxy must be configured to authenticate this resource.": "必须配置 Tor 代理才能验证此资源。",
    "Upgrade Bitcoin Core to v24 or later for Taproot wallet support": "请将 Bitcoin Core 升级到 v24 或更高版本以支持 Taproot 钱包",
    "Error searching for broadcasted notification transaction": "搜索已广播的通知交易时出错",
    "Timeout searching for broadcasted notification transaction": "搜索已广播的通知交易超时",
    "\nThe connection to the Bitcoin Core node was successful, but it is still syncing and cannot be used yet.": "\n与 Bitcoin Core 节点的连接成功，但它仍在同步中，尚不能使用。",
    "Installing udev rules ensures devices can connect over USB.\nThese commands require root privileges.\nOpen a shell and enter the following.": "安装 udev 规则可确保设备能通过 USB 连接。\n这些命令需要 root 权限。\n打开一个终端并输入以下内容。",
    "Could not parse pasted transaction or PSBT": "无法解析粘贴的交易或 PSBT",
    "Property jpackage.app-path is not present": "属性 jpackage.app-path 不存在",
    "\nWarning! You are connected to a public server and sharing your transaction data with it.\nFor better privacy, consider using your own Bitcoin Core node or private Electrum server.": "\n警告！你正在连接到公共服务器，并与其共享你的交易数据。\n为获得更好的隐私，请考虑使用自己的 Bitcoin Core 节点或私有 Electrum 服务器。",
    "This transaction pays a silent payment address.\n\nThe signing device must return the PSBT rather than the signed transaction, as the output address must be calculated after signing.": "此交易支付到静默支付地址。\n\n签名设备必须返回 PSBT 而不是已签名交易，因为输出地址必须在签名后计算。",
    "Wallet load failed: No other public servers available that can serve the open wallets, retrying later...": "钱包加载失败：没有其他可以服务已打开钱包的公共服务器，稍后重试...",
    " but the proof of inclusion it supplied does not match that block.": " 但它提供的包含证明与该区块不匹配。",
    " but the proofs of inclusion it supplied do not match those blocks.": " 但它提供的包含证明与这些区块不匹配。",
    " which then declined to prove it at that height.": " 而它在那个高度拒绝证明。",
    " which then declined to prove them at those heights.": " 而它在那些高度拒绝证明。",
    "Failed to sync block headers, retrying in 60s": "同步区块头失败，60 秒后重试",
    "Connection failed: No public servers available that can serve the open wallets, retrying later...": "连接失败：没有可以服务已打开钱包的公共服务器，稍后重试...",
    "Headless environment detected but headless glass platform not found": "检测到无头环境，但未找到无头 glass 平台",
    "Opening files/URIs in already running instance, exiting...": "在已运行的实例中打开文件/URI，正在退出...",
    "Enter the number of additional accounts to scan for existing funds.\n\nThis may take a few minutes depending on how many accounts are selected.": "输入要扫描现有资金的额外账户数量。\n\n根据所选账户数量，这可能需要几分钟。",
    "Download the release file, GPG signature and optional manifest of a project to verify the download integrity": "下载项目的发布文件、GPG 签名和可选的清单，以验证下载的完整性",
    ", and spending unconfirmed UTXOs is allowed.": "，并允许花费未确认的 UTXO。",
    "The following text needs to be signed by the device.\nClick OK to continue.": "以下文本需要由设备签名。\n点击确定继续。",
    "Only single signature P2PKH, P2SH-P2WPKH or P2WPKH addresses can verify messages.": "只有单签 P2PKH、P2SH-P2WPKH 或 P2WPKH 地址可以验证消息。",
    "Error extracting BIP-322 signature from PSBT": "从 PSBT 提取 BIP-322 签名时出错",
    "Border Wallets Entropy Grid Recovery Seed": "Border Wallets 熵网格恢复助记词",
    "Generated mnemonic words list not same size as displayed words list": "生成的助记词列表与显示的助记词列表大小不一致",
    "A passphrase is not a password! Any variation entered in future loads a valid wallet, but with different addresses.": "密码短语不是密码！将来输入的任何变体都会加载一个有效的钱包，但地址不同。",
    "Advanced feature: a passphrase provides optional added security, but it is not stored so it must be remembered!": "高级功能：密码短语提供可选的安全性，但不会被存储，因此必须牢记！",
    "Native Segwit is usually the best choice for new wallets.\nTaproot is a new type useful for specific needs.\nTaproot Silent Payments creates a silent payment wallet.": "原生 Segwit 通常是新钱包的最佳选择。\nTaproot 是适用于特定需求的新类型。\nTaproot 静默支付会创建静默支付钱包。",
    "The configured server type is Bitcoin Core, which does not support wallet discovery.\n\nYou can however import the wallet file and scan the blockchain by supplying a start date.": "配置的服务器类型是 Bitcoin Core，不支持钱包发现。\n\n不过你可以导入钱包文件并通过提供开始日期扫描区块链。",
    "Could not find an HD wallet with existing transactions using this mnemonic. Import this wallet anyway?": "使用此助记词未找到包含现有交易的 HD 钱包。仍要导入此钱包吗？",
    "The following QR contains these seed words. Be careful before displaying or digitally recording it.\n\nAre you sure you want to continue?": "以下二维码包含这些助记词。在显示或数字记录前请小心。\n\n确定要继续吗？",
    "Send to many recipients by specifying addresses and amounts.\nOnly the first row's label is necessary.": "通过指定地址和金额向多个收款人发送。\n只有第一行的标签是必需的。",
    "SystemTray icons are not supported by the current desktop environment.": "当前桌面环境不支持系统托盘图标。",
    "Select an approximate date earlier than the first wallet transaction.": "选择早于第一笔钱包交易的大致日期。",
    "Skipped execution of webcam capture task, another task is running": "跳过了摄像头捕获任务的执行，另一个任务正在运行",
    "Timed out waiting for task semaphore to be available to cancel, cancelling anyway": "等待任务信号量以取消时超时，仍然取消",
    "Interrupted while waiting for task semaphore to be available to cancel, cancelling anyway": "等待任务信号量以取消时被中断，仍然取消",
    "Tor is already running, using external instance...": "Tor 已在运行，正在使用外部实例...",
    "Could not delete lock file from previous instance": "无法删除先前实例的锁文件",
    "Could not open client connection to existing instance": "无法打开到现有实例的客户端连接",
    "Could not open UNIX socket lock file for instance at " + S: "无法为以下位置的实例打开 UNIX 套接字锁文件 " + S,
    "Could not create symlink " + S + " to lockFile at " + S + ", writing as normal file": "无法创建符号链接 " + S + " 指向位于 " + S + " 的锁文件，将作为普通文件写入",
    "Could not create pointer " + S + " to lockFile at " + S: "无法创建指向位于 " + S + " 锁文件的指针 " + S,
    "Import QR created on your AirGap Vault, by selecting the Secret > Account > Sparrow Wallet": "导入在 AirGap Vault 上通过选择 Secret > Account > Sparrow Wallet 创建的二维码",
    "Error importing BSMS: Invalid mnemonic checksum": "导入 BSMS 时出错：助记词校验和无效",
    "Provided password needs to be in hexadecimal, decimal or mnemonic format.": "提供的密码必须是十六进制、十进制或助记词格式。",
    "Signature did not match provided public key": "签名与提供的公钥不匹配",
    "This file does not provide a first address, so the descriptor cannot be verified against the other signers in the quorum": "此文件未提供第一个地址，因此无法对照法定人数中的其他签名者验证描述符",
    "Generate or import your 12 to 24 word mnemonic and optional passphrase.": "生成或导入你的 12 至 24 个助记词及可选的密码短语。",
    "Import your Codex32 secret share. Only a single share is currently supported.": "导入你的 Codex32 秘密份额。目前仅支持单个份额。",
    "Import file or QR created by using the Wallet > Export Coordination Setup feature on your BlueWallet Vault": "导入在 BlueWallet Vault 上通过 Wallet > Export Coordination Setup 功能创建的文件或二维码",
    "Export file that can be read by BlueWallet using the Add Wallet > Vault > Import wallet feature.": "导出可通过 BlueWallet 的 Add Wallet > Vault > Import wallet 功能读取的文件。",
    "Import the file created via the Download Wallet Details button in Caravan.": "导入通过 Caravan 中的 Download Wallet Details 按钮创建的文件。",
    "Export a file that can be imported via the Import Wallet Configuration button in Caravan.": "导出可通过 Caravan 中的 Import Wallet Configuration 按钮导入的文件。",
    "Import file or QR created by using the Multisig Wallet > ... > Show/Export XPUB feature on your Cobo Vault": "导入在 Cobo Vault 上通过 Multisig Wallet > ... > Show/Export XPUB 功能创建的文件或二维码",
    "Import file or QR created by using the Multisig Wallet > ... > Create Multisig Wallet feature on your Cobo Vault": "导入在 Cobo Vault 上通过 Multisig Wallet > ... > Create Multisig Wallet 功能创建的文件或二维码",
    "Export file or QR that can be read by your Cobo Vault using the Multisig Wallet > ... > Import Multisig Wallet feature.": "导出可通过 Cobo Vault 的 Multisig Wallet > ... > Import Multisig Wallet 功能读取的文件或二维码。",
    "Import file or QR created by using the My Cobo Vault > ... > Export Wallet feature on your Cobo Vault.": "导入在 Cobo Vault 上通过 My Cobo Vault > ... > Export Wallet 功能创建的文件或二维码。",
    "Import file or QR created by using Settings > Multisig Wallets > [Wallet Detail] > Coldcard Export on your Coldcard.": "导入在 Coldcard 上通过 Settings > Multisig Wallets > [Wallet Detail] > Coldcard Export 创建的文件或二维码。",
    "Export file or QR that can be read by your Coldcard using Settings > Multisig Wallets > Import from File or QR.": "导出可通过 Coldcard 的 Settings > Multisig Wallets > Import from File or QR 读取的文件或二维码。",
    "The output descriptor is a standardized description of the wallet compatible with Bitcoin Core, and can be used to restore the wallet in Sparrow and other wallets.": "输出描述符是兼容 Bitcoin Core 的标准化钱包描述，可用于在 Sparrow 和其他钱包中恢复钱包。",
    "Import a file containing the output descriptor of a wallet. The output descriptor is a standardized description of the wallet compatible with Bitcoin Core, and can be used to restore the wallet in Sparrow and other wallets.": "导入包含钱包输出描述符的文件。输出描述符是兼容 Bitcoin Core 的标准化钱包描述，可用于在 Sparrow 和其他钱包中恢复钱包。",
    "Could not find an output descriptor in the file": "文件中未找到输出描述符",
    "Multisig wallet detected - import it using File > Import Wallet": "检测到多签钱包 - 请使用 文件 > 导入钱包 导入",
    "Electrum does not support exporting BIP39 derived seeds, as it does not store the mnemonic words. Only seeds entered directly into Electrum as xprv can be exported.": "Electrum 不支持导出 BIP39 派生的助记词，因为它不存储助记词。只有直接以 xprv 形式输入 Electrum 的助记词才能导出。",
    "Export this wallet as an Electrum wallet file.": "将此钱包导出为 Electrum 钱包文件。",
    "# Electrum Personal Server configuration file fragments": "# Electrum Personal Server 配置文件片段",
    "# First close Sparrow and edit your config file in Sparrow home to set \"legacyServer\": true": "# 首先关闭 Sparrow，在 Sparrow 主目录中编辑配置文件，将 \"legacyServer\" 设为 true",
    "# Then copy the lines below into the relevant sections in your EPS config.ini file\n\n": "# 然后将以下行复制到 EPS config.ini 文件的相关部分\n\n",
    "# Copy into [master-public-keys] section\n\n": "# 复制到 [master-public-keys] 部分\n\n",
    "\n# Copy into [watch-only-addresses] section\n": "\n# 复制到 [watch-only-addresses] 部分\n",
    "\n# Important: If this wallet receives any BIP47 payments, redo this export": "\n# 重要提示：如果此钱包收到任何 BIP47 支付，请重新执行此导出",
    "Import QR created on your ERA Wallet by opening your wallet and selecting Link > Sparrow from the wallet menu": "导入在 ERA Wallet 上通过打开钱包并从钱包菜单中选择 Link > Sparrow 创建的二维码",
    "BitBox02 attestation check failed, device may not be genuine": "BitBox02 认证检查失败，设备可能不是正品",
    "This BitBox02 did not pass the attestation check, which means it may not be a genuine device.\n\nDo not use this device to store funds!": "此 BitBox02 未通过认证检查，这意味着它可能不是正品设备。\n\n请勿使用此设备存储资金！",
    "Import QR created on your Jade by selecting Options > Wallet > Export Xpub once you have loaded your seed": "导入在 Jade 上加载助记词后通过选择 Options > Wallet > Export Xpub 创建的二维码",
    "Export a QR that allows Jade to import a multisig wallet using the Scan feature.": "导出一个二维码，使 Jade 可以使用扫描功能导入多签钱包。",
    "Import the QR created using Options > Wallet > Registered Wallets on your Jade.": "导入在 Jade 上使用 Options > Wallet > Registered Wallets 创建的二维码。",
    "Import QR created on your Keycard Shell by selecting Connect software wallet > Bitcoin MultiSig": "导入在 Keycard Shell 上通过选择 Connect software wallet > Bitcoin MultiSig 创建的二维码",
    "Import file or QR created by using the Multisig Wallet > ... > Show/Export XPUB feature on your Keystone.": "导入在 Keystone 上通过 Multisig Wallet > ... > Show/Export XPUB 功能创建的文件或二维码。",
    "Import file or QR created by using the Multisig Wallet > ... > Create Multisig Wallet feature on your Keystone.": "导入在 Keystone 上通过 Multisig Wallet > ... > Create Multisig Wallet 功能创建的文件或二维码。",
    "Export file or QR that can be read by your Keystone using the Multisig Wallet > ... > Import Multisig Wallet feature.": "导出可通过 Keystone 的 Multisig Wallet > ... > Import Multisig Wallet 功能读取的文件或二维码。",
    "Import file or QR created by using the My Keystone > ... > Export Wallet feature on your Keystone. Make sure to set the Watch-only Wallet to Sparrow in the Settings first.": "导入在 Keystone 上通过 My Keystone > ... > Export Wallet 功能创建的文件或二维码。请务必先在设置中将只观察钱包设置为 Sparrow。",
    "Output descriptor describes a multisig wallet": "输出描述符描述的是多签钱包",
    "Import file or QR created by selecting Extended Public Key from the main menu once you have loaded your seed": "加载助记词后从主菜单中选择 Extended Public Key 创建的文件或二维码",
    "Import file or QR created from Manage Account > Connect Wallet > Sparrow > Multisig > QR Code/microSD on your Passport": "导入在 Passport 上通过 Manage Account > Connect Wallet > Sparrow > Multisig > QR Code/microSD 创建的文件或二维码",
    "As part of the Multisig connection flow, Passport will ask you to scan or import the multisig configuration file exported by Sparrow.": "作为多签连接流程的一部分，Passport 会要求你扫描或导入由 Sparrow 导出的多签配置文件。",
    "Import file or QR created by using Settings > Bitcoin > Multisig > [Wallet Detail] > Export via QR/microSD on your Passport": "导入在 Passport 上通过 Settings > Bitcoin > Multisig > [Wallet Detail] > Export via QR/microSD 创建的文件或二维码",
    "Import file or QR created from Manage Account > Connect Wallet > Sparrow > Single-sig > QR Code/microSD on your Passport": "导入在 Passport 上通过 Manage Account > Connect Wallet > Sparrow > Single-sig > QR Code/microSD 创建的文件或二维码",
    "You have chosen to not save the entropy grid PDF.\n\nDo not store funds on a seed selected from this grid - it will be lost!": "你选择不保存熵网格 PDF。\n\n请不要在从此网格选出的助记词上存储资金 - 它会丢失！",
    "Import the wallet backup file samourai.txt exported from the Samourai app. Note that see the full balance requires a Bitcoin Core node.": "导入从 Samourai 应用导出的钱包备份文件 samourai.txt。请注意，查看完整余额需要 Bitcoin Core 节点。",
    "Failed to decrypt the wallet backup file, check if the password is correct.": "解密钱包备份文件失败，请检查密码是否正确。",
    "Import QR created on your SeedSigner by selecting Export Xpub in the Seeds menu once you have entered your seed": "导入在 SeedSigner 上输入助记词后从 Seeds 菜单选择 Export Xpub 创建的二维码",
    "Import your 20 or 33 word mnemonic shares and optional passphrase.": "导入你的 20 或 33 个助记词份额及可选的密码短语。",
    "Exports your Sparrow wallet file, which can be imported into another Sparrow instance running on any supported platform.": "导出你的 Sparrow 钱包文件，可导入到在任何受支持平台上运行的另一个 Sparrow 实例中。",
    "Imports an exported Sparrow wallet file into Sparrow's wallets folder.": "将导出的 Sparrow 钱包文件导入 Sparrow 的钱包文件夹。",
    "Export a Specter wallet that can be read by Specter Desktop using Add new wallet > Import from wallet software.": "导出一个可由 Specter Desktop 通过 Add new wallet > Import from wallet software 读取的 Specter 钱包。",
    "Could not determine keystore from import": "无法从导入确定密钥库",
    "Import file or QR created by using the Master Public Keys feature on your Specter DIY device. Note the derivation path.": "导入在 Specter DIY 设备上通过 Master Public Keys 功能创建的文件或二维码。注意派生路径。",
    "Export file or QR that can be read by your Specter DIY using the Wallets > Add Wallet feature.": "导出可通过 Specter DIY 的 Wallets > Add Wallet 功能读取的文件或二维码。",
    "Import file or QR created by using the Multisig Wallet > Settings > Export Wallet Descriptor feature on your Specter DIY device.": "导入在 Specter DIY 设备上通过 Multisig Wallet > Settings > Export Wallet Descriptor 功能创建的文件或二维码。",
    "Derived pubkey does not match stored pubkey": "派生的公钥与存储的公钥不匹配",
    "Exports a file containing labels from this wallet in the BIP329 standard format.": "导出包含此钱包标签的文件，格式为 BIP329 标准。",
    "Exports a CSV file containing dates and values of the transactions in this wallet. Additionally, if a fiat currency has been set, a fiat value will be included.": "导出包含此钱包交易日期和值的 CSV 文件。此外，如果已设置法币，将包含法币价值。",
    "Compressed data was larger than uncompressed data": "压缩数据大于未压缩数据",
    "Card authentication failure: Provided signature did not match public key": "卡片身份验证失败：提供的签名与公钥不匹配",
    "Card authentication failure: Could not verify to root certificate": "卡片身份验证失败：无法验证根证书",
    "Card did not accept the request to wait out the authentication delay.": "卡片未接受等待身份验证延迟结束的请求。",
    "Card cannot recognise public key for signing address.": "卡片无法识别签名地址的公钥。",
    "Card authentication failed: Provided pubkey does not match given address": "卡片身份验证失败：提供的公钥与给定地址不匹配",
    "Serialization of Java objects is not supported in wallet files.": "钱包文件中不支持 Java 对象序列化。",
    "Deserialization of Java objects is not supported in wallet files.": "钱包文件中不支持 Java 对象反序列化。",
    "Could not open wallet file store for validation, deferring to standard open": "无法打开钱包文件存储进行验证，推迟到标准打开",
    "This is not a valid wallet file.\n\nWallet file could not be validated.": "这不是有效的钱包文件。\n\n钱包文件无法验证。",
    "This is not a valid wallet file.\n\nWallet file contains unexpected database objects.": "这不是有效的钱包文件。\n\n钱包文件包含意外的数据库对象。",
    "Failed to open wallet file. Validation error during schema migration.": "打开钱包文件失败。架构迁移期间出现验证错误。",
    "Wallet file may already be in use. Make sure the application is not running elsewhere.": "钱包文件可能已被使用。请确保应用程序没有在其他地方运行。",
    "Not persisting update for missing schema": "不持久化对缺失架构的更新",
    "Only absolute paths can be set as PINLESS path": "只能将绝对路径设置为 PINLESS 路径",
    "Truncated TLV: no length byte at offset": "截断的 TLV：偏移处没有长度字节",
    "Truncated TLV: length header of " + S + " bytes is unsupported or exceeds the " + S + " bytes remaining": "截断的 TLV：" + S + " 字节的长度头不受支持或超过剩余 " + S + " 字节",
    "Truncated TLV: declared length of " + S + " exceeds the " + S + " bytes remaining": "截断的 TLV：声明的长度 " + S + " 超过剩余 " + S + " 字节",
    "Could not authenticate. Callback URL of " + S + " returned a 404 response.": "无法进行身份验证。" + S + " 的回调 URL 返回 404 响应。",
    "Failed to retrieve transaction history for paths:": "检索路径的交易历史失败：",
    "Failed to retrieve mempool transactions for paths:": "检索路径的内存池交易失败：",
    "Failed to unsubscribe from script hashes:": "取消订阅脚本哈希失败：",
    "Failed to retrieve block headers for block heights:": "检索这些区块高度的区块头失败：",
    "Failed to retrieve block stats for block heights:": "检索这些区块高度的区块统计失败：",
    "Failed to retrieve transactions for txids:": "检索这些 txid 的交易失败：",
    "Failed to retrieve verbose transactions for txids:": "检索这些 txid 的详细交易失败：",
    "Failed to retrieve block headers for start heights:": "检索这些起始高度的区块头失败：",
    "Error getting fee estimates from connected server:": "从已连接服务器获取手续费估算时出错：",
    "Error getting fee estimates for target blocks:": "获取目标区块的手续费估算时出错：",
    "Could not load block explorer image for ": "无法为以下项目加载区块浏览器图像 ",
    "Could not retrieve txid from broadcast, server returned:": "无法从广播中检索 txid，服务器返回：",
    "Could not broadcast transaction, server returned :": "无法广播交易，服务器返回：",
    "Could not load bwt from java.home, falling back to JAR extraction": "无法从 java.home 加载 bwt，回退到 JAR 提取",
    "Error subscribing to recent mempool transactions": "订阅最近的内存池交易时出错",
    "Bitcoin Core requires Multi-Wallet to be enabled in the Server Settings": "Bitcoin Core 要求在服务器设置中启用多钱包",
    "Wallet file verification failed. Refusing to load database.": "钱包文件验证失败。拒绝加载数据库。",
    "Bitcoin Core wallet file verification failed. Try restarting Bitcoin Core.": "Bitcoin Core 钱包文件验证失败。请尝试重新启动 Bitcoin Core。",
    "This error could be caused by pruning or data corruption": "此错误可能是由修剪或数据损坏引起的",
    "Scanning failed. Bitcoin Core is pruned to a date after the wallet birthday.": "扫描失败。Bitcoin Core 已修剪到钱包出生日期之后的日期。",
    "Check if Bitcoin Core is running, and the authentication details are correct.": "请检查 Bitcoin Core 是否正在运行，以及身份验证信息是否正确。",
    "Cannot start cormorant: " + S + ". Starting BWT...": "无法启动 cormorant：" + S + "。正在启动 BWT...",
    "Error subscribing to recent mempool transaction outputs": "订阅最近的内存池交易输出时出错",
    "Could not determine payment code for notification transaction": "无法确定通知交易的支付码",
    "Invalid notification transaction creates illegal payment code": "无效的通知交易创建了非法的支付码",
    "Electrum server certificate file not found": "未找到 Electrum 服务器证书文件",
    "All used nodes on a non-empty wallet have changed history. Triggering a full wallet refresh.": "非空钱包上所有已使用的节点都更改了历史。正在触发完整钱包刷新。",
    "Interrupted while verifying transactions": "验证交易时被中断",
    "Could not write to the block header store": "无法写入区块头存储",
    "Could not retrieve referenced transactions": "无法检索引用的交易",
    "This server does not support silent payments": "此服务器不支持静默支付",
    "Interrupted waiting for silent payments subscription to establish": "等待静默支付订阅建立时被中断",
    "Interrupted waiting for silent payments scan to complete": "等待静默支付扫描完成时被中断",
    "Warning: Ignoring invalid block header announced by the server": "警告：忽略服务器宣布的无效区块头",
    "Could not read the block header store:": "无法读取区块头存储：",
    "Could not verify the header chain to height :": "无法验证到该高度的头链：",
    "Invalid silent payment tweak for tx " + S + " — skipping": "交易 " + S + " 的静默支付 tweak 无效 — 跳过",
    "Silent payment child already exists at index": "静默支付子项已存在于该索引",
    "Could not load exchange source image for ": "无法为以下项目加载汇率源图像 ",
    "Height = " + S + ", timestamp = " + S + ": both must be specified": "高度 = " + S + "，时间戳 = " + S + "：两者都必须指定",
    S + " does not support retrieving the next block median fee rate": S + " 不支持检索下一个区块的中位手续费率",
    S + " does not support recent mempool transactions": S + " 不支持最近的内存池交易",
    "Could not load fee rates source image for ": "无法为以下项目加载手续费率源图像 ",
    "Discarding the block header store at " + S + ": it does not descend from the checkpoint at height " + S: "丢弃位于 " + S + " 的区块头存储：它不是从高度 " + S + " 的检查点派生的",
    "Could not delete the block header store at " + S: "无法删除位于 " + S + " 的区块头存储",
    "Could not delete the superseded block header store at " + S: "无法删除位于 " + S + " 的已被取代的区块头存储",
    "Height " + S + " is outside the store range " + S + " to " + S: "高度 " + S + " 超出存储范围 " + S + " 到 " + S,
    "The block header store could not be re-verified to height " + S + ", reaching only height " + S: "区块头存储无法重新验证到高度 " + S + "，仅达到高度 " + S,
    "Could not create the block header store at " + S: "无法在 " + S + " 创建区块头存储",
    "Dropping the block header store above height " + S + ":": "正在丢弃高度 " + S + " 以上的区块头存储：",
    "Avoiding local DNS resolution of " + S + ", assuming it is a non-local address to be resolved by the configured proxy": "避免对 " + S + " 进行本地 DNS 解析，假定它是将由配置的代理解析的非本地地址",
    ", assuming it is a non-local address to be resolved by the configured proxy": "，假定它是将由配置的代理解析的非本地地址",
    "Parameter k1 was absent or of incorrect length.": "参数 k1 缺失或长度不正确。",
    "Parameter k1 was not a valid hexadecimal value.": "参数 k1 不是有效的十六进制值。",
    "Only singlesig HD wallets can authenticate.": "只有单签 HD 钱包可以进行身份验证。",
    "The filename has to be at least 3 characters long.": "文件名必须至少为 3 个字符。",
    "No such mempool or blockchain transaction": "没有这样的内存池或区块链交易",
    "Failed to retrieve transaction history for path:": "检索该路径的交易历史失败：",
    "Failed to retrieve mempool transactions for path:": "检索该路径的内存池交易失败：",
    "Failed to unsubscribe from script hash:": "取消订阅脚本哈希失败：",
    "Failed to retrieve block header for block height:": "检索该区块高度的区块头失败：",
    "Failed to retrieve block stats for block height:": "检索该区块高度的区块统计失败：",
    "Failed to retrieve transaction for txid []": "检索该 txid 的交易失败 []",
    "Failed to retrieve merkle proof for transaction []": "检索该交易的 merkle 证明失败 []",
    "Failed to retrieve fee rate for target blocks:": "检索目标区块的手续费率失败：",
    "Received script hash status update, but status has not changed": "收到脚本哈希状态更新，但状态未改变",
    "Received script hash status update for non-wallet script hash:": "收到非钱包脚本哈希的状态更新：",
    "Status updated for script hash " + S + ", was " + S + " now " + S: "脚本哈希 " + S + " 的状态已更新，原为 " + S + "，现在为 " + S,
    "Received silent payments notification for unknown subscription:": "收到未知订阅的静默支付通知：",
    "Attempting to retrieve certificate for unverified peer": "正在尝试为未验证的对等方检索证书",
    "Certificate for " + S + " at " + S + " is not yet valid, check the system clock is correct": S + " 在 " + S + " 的证书尚无效，请检查系统时钟是否正确",
    "Socket connection has not been established.": "套接字连接尚未建立。",
    "No response from server, setting read timeout to " + S + " secs": "服务器无响应，将读取超时设置为 " + S + " 秒",
    "Could not parse JSON-RPC message from server:": "无法解析来自服务器的 JSON-RPC 消息：",
    "Provided server certificate from " + S + " did not match configured certificate at " + S: S + " 提供的服务器证书与位于 " + S + " 的配置证书不匹配",
    "Provided server certificate from " + S + " did not match previously saved certificate at " + S: S + " 提供的服务器证书与位于 " + S + " 的先前保存的证书不匹配",
    "Provided server certificate from " + S + " failed CA validation": S + " 提供的服务器证书未通过 CA 验证",
    "Provided server certificate from " + S + " was invalid: " + S: S + " 提供的服务器证书无效：" + S,
    "Can't create Tor socket, Tor is not running": "无法创建 Tor 套接字，Tor 未运行",
    "Tor ControlPort failed SAFECOOKIE server hash verification": "Tor ControlPort 未通过 SAFECOOKIE 服务器哈希验证",
    "Refusing to connect to non-loopback Tor ControlPort at ": "拒绝连接到非回环地址的 Tor ControlPort ",
    "Error authenticating to Tor at " + S + ", server returned " + S: "在 " + S + " 处向 Tor 进行身份验证时出错，服务器返回 " + S,
    "Timeout reading from " + S + ", is this a Tor ControlPort?": "从 " + S + " 读取超时，这是 Tor ControlPort 吗？",
    "Permission denied reading Tor cookie file at ": "读取位于以下位置的 Tor cookie 文件时权限被拒绝 ",
    "Error connecting to " + S + ", no Tor ControlPort configured?": "连接到 " + S + " 时出错，未配置 Tor ControlPort？",
    "Invalid signature for version check " + S + " from address " + S: "来自地址 " + S + " 的版本检查签名无效 " + S,
    "Scanning silent payment wallets is not currently supported with Bitcoin Core": "当前不支持使用 Bitcoin Core 扫描静默支付钱包",
    "Attempting to check if an address is imported, but Cormorant is not started": "正在尝试检查地址是否已导入，但 Cormorant 未启动",
    "Attempting to check if " + S + " is imported, but Cormorant is not started": "正在尝试检查 " + S + " 是否已导入，但 Cormorant 未启动",
    "Reorg detected, block height " + S + " was " + S + " and now is " + S: "检测到重组，区块高度 " + S + " 原为 " + S + "，现在为 " + S,
    "Bitcoin Core data folder or user and password is required": "需要 Bitcoin Core 数据文件夹或用户名和密码",
    "Bitcoin Core versions older than v24 are not supported": "不支持早于 v24 的 Bitcoin Core 版本",
    "Error while waiting for sync to complete": "等待同步完成时出错",
    "Interrupted while waiting for sync to complete": "等待同步完成时被中断",
    "Wallet support must be enabled in Bitcoin Core": "必须在 Bitcoin Core 中启用钱包支持",
    "Address birth date earlier than prune date.": "地址出生日期早于修剪日期。",
    "Error: Wallet birthday earlier than Bitcoin Core prune date": "错误：钱包出生日期早于 Bitcoin Core 修剪日期",
    "Bitcoin Core returned " + S + " results for " + S + " imported descriptors": "Bitcoin Core 为 " + S + " 个导入的描述符返回了 " + S + " 个结果",
    "Could not retrieve certificate for saving": "无法检索要保存的证书",
    "Could not parse JSON-RPC request method, applying the default read timeout:": "无法解析 JSON-RPC 请求方法，应用默认读取超时：",
    "Could not communicate with client socket": "无法与客户端套接字通信",
    "The receiver added some inputs but could not bump the fee of the payjoin proposal.": "接收方添加了一些输入，但无法提高 payjoin 提案的手续费。",
    "The receiver rejected the original PSBT.": "接收方拒绝了原始 PSBT。",
    "Original PSBT for payjoin transaction cannot contain silent payment outputs": "payjoin 交易的原始 PSBT 不能包含静默支付输出",
    "Original PSBT for payjoin transaction must have non_witness_utxo or witness_utxo fields for all inputs": "payjoin 交易的原始 PSBT 必须为所有输入包含 non_witness_utxo 或 witness_utxo 字段",
    "Original PSBT for payjoin transaction must be finalized": "payjoin 交易的原始 PSBT 必须已完成",
    "Global xpubs should not be included in the receiver's PSBT": "全局 xpub 不应包含在接收方的 PSBT 中",
    "The proposal PSBT changed the transaction version": "提案 PSBT 更改了交易版本",
    "The receiver added partial signatures to an input": "接收方向输入添加了部分签名",
    "The proposed transaction input modified the sequence of one of the original inputs": "提议的交易输入修改了原始输入之一的序号",
    "The receiver finalized one of the original inputs": "接收方完成了原始输入之一的签名",
    "The receiver did not finalize one of their inputs": "接收方未完成其输入之一的签名",
    "The receiver did not specify non_witness_utxo or witness_utxo for one of their inputs": "接收方未为其输入之一指定 non_witness_utxo 或 witness_utxo",
    "Some of the original inputs are not included in the proposal": "部分原始输入未包含在提案中",
    "Mixed sequences detected in the proposal": "在提案中检测到混合的序号",
    "The receiver added keypaths to an output": "接收方向输出添加了密钥路径",
    "The actual contribution is more than maxadditionalfeecontribution": "实际贡献超过 maxadditionalfeecontribution",
    "The actual contribution is not only paying fee": "实际贡献不只是支付手续费",
    "The actual contribution is not only paying for additional inputs": "实际贡献不只是支付额外输入",
    "Some of our outputs are not included in the proposal": "我们的一些输出未包含在提案中",
    "Configure a Tor proxy to get a payjoin transaction from " + S + ".": "配置 Tor 代理以从 " + S + " 获取 payjoin 交易。",
    "Payjoin receiver returned a status of " + S + " with an unrecognised body": "payjoin 接收方返回状态 " + S + "，且正文无法识别",
    "Could not find resource at payjoin URL": "在 payjoin URL 处找不到资源",
    "Proposal script type of " + S + " did not match wallet script type of " + S: "提案的脚本类型 " + S + " 与钱包的脚本类型 " + S + " 不匹配",
    "The receiver decreased the value of one of the outputs from " + S + " sats to " + S + " sats": "接收方将其中一个输出的价值从 " + S + " 聪降低到 " + S + " 聪",
    "The fee rate of the payjoin transaction of " + S + " sats/vB is less than the requested minimum of " + S + " sats/vB": "payjoin 交易的手续费率 " + S + " sats/vB 低于请求的最低 " + S + " sats/vB",
    "Error creating PayNym from payment code ": "从支付码创建 PayNym 时出错 ",
    "Enter the URL of the block explorer.\n\nIf present, the characters {0} will be replaced with the txid.\nFor": "输入区块浏览器的 URL。\n\n如果存在，字符 {0} 将被替换为 txid。\n对于",
    "Configure aliases for recently connected servers.\nNew servers are added to this list on successful connection.": "为最近连接的服务器配置别名。\n新服务器在成功连接后添加到该列表。",
    "Your IP address will be visible to the node.\n\n": "你的 IP 地址将对节点可见。\n\n",
    "\nThe RPC credentials and wallet descriptors sent to it are unencrypted, and can be read by anyone on the network.": "\n发送给它的 RPC 凭据和钱包描述符未加密，网络上的任何人都可以读取。",
    "\nThe certificate presented by the node on the first connection will be trusted and required on all subsequent connections.": "\n节点在首次连接时出示的证书将被信任，并在所有后续连接中要求使用。",
    "\nConnecting to the Bitcoin Core RPC interface over an untrusted network is not recommended by either Sparrow or Bitcoin Core.": "\nSparrow 和 Bitcoin Core 都不建议通过不受信任的网络连接 Bitcoin Core RPC 接口。",
    "Consider using a node on this computer or your local network, connecting over a Tor onion address, or tunnelling with SSH or a VPN.": "请考虑使用此计算机或本地网络上的节点，通过 Tor 洋葱地址连接，或使用 SSH 或 VPN 进行隧道连接。",
    " on the server. Check that the onion address and port are correct, and that both Tor and the Electrum server are running.": " 在服务器上。请检查洋葱地址和端口是否正确，以及 Tor 和 Electrum 服务器是否都在运行。",
    "\nMake sure server=1 has been added to bitcoin.conf": "\n请确保已将 server=1 添加到 bitcoin.conf",
    "Bitcoin Core at  this computer or your local network.": "Bitcoin Core 位于此计算机或你的本地网络。",
    "\nConnections to Bitcoin Core are made directly, and the  is only used for onion addresses.": "\n与 Bitcoin Core 的连接是直接的，仅用于洋葱地址。",
    "Re-enter the BIP39 passphrase\nto confirm:": "重新输入 BIP39 密码短语\n以确认：",
    "An extended private key cannot be used to create a watch only wallet. Enter an extended public key, or an address to watch.": "不能使用扩展私钥创建只观察钱包。请输入扩展公钥或要观察的地址。",
    "Error subscribing FinalizingPSBTWallet script hashes": "订阅 FinalizingPSBTWallet 脚本哈希时出错",
    "A sighash value of none means the signature does not commit to any of the outputs, and can be reused on a transaction with different outputs.": "Sighash 值为 none 表示签名不承诺任何输出，可在具有不同输出的交易上重复使用。",
    "Failed to retrieve all referenced input transactions, aborting transaction fetch": "检索所有引用的输入交易失败，正在中止交易获取",
    "The scanned seed does not have a valid checksum, which usually indicates a scanning or transcription error. Other wallets will not accept it, so any funds sent to this keystore may not be recoverable from a backup of these words.": "扫描到的助记词没有有效的校验和，这通常表示扫描或抄写错误。其他钱包不会接受它，因此发送到此密钥库的任何资金可能无法通过这些助记词的备份恢复。",
    "\nKey expressions are shown in canonical order.": "\n密钥表达式按规范顺序显示。",
    "Sparrow supports BIP67 compatible multisig wallets only.\n\nThe public keys will be lexicographically sorted and the descriptors will be amended if necessary.": "Sparrow 仅支持 BIP67 兼容的多签钱包。\n\n公钥将按字典顺序排序，描述符将视情况进行修正。",
    "Sparrow will convert the provided private key to a public key for use in a watch only wallet.\n\nTo import": "Sparrow 会将提供的私钥转换为公钥，用于只观察钱包。\n\n要导入",
    "Sparrow does not support non-BIP32 wallets without standard receive and change chains.\n\nThe provided desc": "Sparrow 不支持没有标准接收链和找零链的非 BIP32 钱包。\n\n所提供的描述符",
    "This import completes the configuration of ": "此导入完成了以下配置 ",
    " configured here is not present in this import and will be removed. You will not be able to sign with it.": " 在此处配置的内容不在此导入中，将被移除。你将无法使用它签名。",
    "\nVerify the quorum and the cosigner key origins above against those provided by the coordinator before applying.": "\n应用前，请将上述法定人数和共同签名密钥来源与协调器提供的进行核对。",
    "Note the configured server type is Bitcoin Core, which does not support account discovery.": "注意配置的服务器类型是 Bitcoin Core，不支持账户发现。",
    "You are changing the script type on a wallet with existing key information. Usually this means the keys need to be re-imported using a different derivation path.": "你正在更改包含现有密钥信息的钱包的脚本类型。这通常意味着需要使用不同的派生路径重新导入密钥。",
    "Only SettingsWalletForm supports setWallet": "只有 SettingsWalletForm 支持 setWallet",
    "It appears that the history of this wallet has changed, which may be caused by an incorrect passphrase. No new transactions are shown.": "此钱包的历史似乎已更改，这可能是由错误的密码短语引起的。不显示新交易。",
    "Removing and not notifying incomplete entry " + S + " value " + S + " children": "移除且不通知不完整的条目 " + S + " 值 " + S + " 子项",
    "a passphrase provides optional added security, but it is not stored so it must be remembered!": "密码短语提供可选的安全性，但不会被存储，因此必须牢记！",
    "Re-enter the wallet password": "重新输入钱包密码",
}

B2 = {}
for k, v in B.items():
    B2[k.replace(S, "\x01")] = v.replace(S, "\x01")

compared = set()
for line in open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "_work", "compared.txt"), encoding="utf-8"):
    line = line.strip()
    if line.startswith("'") or line.startswith('"'):
        s = line.strip("'\"")
        if s:
            compared.add(s)
drop = [k for k in B2 if k in compared]
print("batch5 keys in compared.txt (dropped):", len(drop))
for k in drop:
    print("  -", repr(k[:60]))
    del B2[k]

json.dump(B2, open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "_work", "java_trans_batch5.json"), "w", encoding="utf-8"), ensure_ascii=True, indent=1)
print("batch5 entries:", len(B2))
