# -*- coding: utf-8 -*-
"""Batch4: full literals with exact ctrl-char positions (missed in batch3 due to
prefix/suffix differences) + visible UI strings. Placeholder \ue001 -> \x01."""
import json, os

S = "\ue001"

B = {
    S + " does not support receiving silent payments": S + " 不支持接收静默支付",
    "The certificate file at " + S + " could not be deleted.\n\nPlease delete this file manually.": "位于 " + S + " 的证书文件无法删除。\n\n请手动删除此文件。",
    "The certificate provided by the server at " + S + " appears to have changed.\n\nThis may indicate a man-in-the-middle attack!\n\nDo you still want to proceed?": "服务器在 " + S + " 提供的证书似乎已更改。\n\n这可能表明存在中间人攻击！\n\n仍要继续吗？",
    "The certificate provided by the server at " + S + " appears to have changed.\n\nThis may be simply due to a certificate renewal, or it may indicate a man-in-the-middle attack.\n\nDo you still want to proceed?": "服务器在 " + S + " 提供的证书似乎已更改。\n\n这可能只是由于证书续期，也可能表明存在中间人攻击。\n\n仍要继续吗？",
    "The certificate provided by the server at " + S + " has expired. " + S + ".\n\nDo you still want to proceed?": "服务器在 " + S + " 提供的证书已过期。" + S + "。\n\n仍要继续吗？",
    "The configured server certificate at " + S + " did not match the certificate provided by the server at " + S + ".\n\nThis may be simply due to a certificate renewal, or it may indicate a man-in-the-middle attack.\n\nChange the configured server certificate if you would like to proceed.": "在 " + S + " 配置的服务器证书与服务器在 " + S + " 提供的证书不匹配。\n\n这可能只是由于证书续期，也可能表明存在中间人攻击。\n\n如要继续，请更改配置的服务器证书。",
    S + "\n\nSee https://sparrowwallet.com/docs/connect-node.html": S + "\n\n参见 https://sparrowwallet.com/docs/connect-node.html",
    "Connecting " + S + "...": "正在连接 " + S + "...",
    "Connecting to " + S + "...": "正在连接到 " + S + "...",
    "Output #" + S: "输出 #" + S,
    "Output #" + S + " value": "输出 #" + S + " 值",
    "Output #" + S + " scriptPubKey length": "输出 #" + S + " scriptPubKey 长度",
    "Output #" + S + " scriptPubKey": "输出 #" + S + " scriptPubKey",
    " at height " + S: " 高度 " + S,
    "Connected to " + S + S + S: "已连接到 " + S + S + S,
    S + "\n\nReview this PSBT carefully before signing.\n\nOpen the transaction?": S + "\n\n签名前请仔细审阅此 PSBT。\n\n打开此交易？",
    "This transaction contains " + S + " of a non-standard or unrecognised script type, totalling " + S + ".\n\nSparrow cannot resolve these outputs to addresses, so they will not appear in the transaction diagram. Review the individual output(s) in the transaction tree carefully before signing or broadcasting.\n\nOpen the transaction?": "此交易包含 " + S + " 个非标准或无法识别的脚本类型输出，总计 " + S + "。\n\nSparrow 无法将这些输出解析为地址，因此它们不会出现在交易图中。请在签名或广播前仔细审阅交易树中的各个输出。\n\n打开此交易？",
    "Wallet file " + S + " already exists.": "钱包文件 " + S + " 已存在。",
    "Delete " + S + "?": "删除 " + S + "？",
    "Sparrow - " + S: "Sparrow - " + S,
    "New " + S + " mempool transaction" + S + S: "新的 " + S + " 笔内存池交易" + S + S,
    "Confirming " + S + " transaction" + S + S: "正在确认 " + S + " 笔交易" + S + S,
    "The connected node is pruned at " + S + ", but the wallet birthday for " + S + " is set to " + S + ".": "已连接节点在 " + S + " 处修剪，但钱包 " + S + " 的出生日期设置为 " + S + "。",
    "Bitcoin Core did not import " + S + ":\n\n" + S + "\n\nTransactions and balances may be incomplete until the import succeeds.": "Bitcoin Core 未能导入 " + S + "：\n\n" + S + "\n\n在导入成功之前，交易和余额可能不完整。",
    "Could not delete " + S + ". Please delete this file manually.": "无法删除 " + S + "。请手动删除此文件。",
    "Open a" + S + S + " wallet to " + S + ".": "打开一个" + S + S + "钱包以 " + S + "。",
    "This wallet is using the derivation path for " + S + ", instead of the derivation path for its defined script type of " + S + ". \n\nDisable derivation path validation to import this wallet?": "此钱包正在使用 " + S + " 的派生路径，而不是其定义脚本类型 " + S + " 的派生路径。\n\n是否禁用派生路径验证以导入此钱包？",
    S + " transactions, the first being " + S + " in block " + S + ", were reported as confirmed by the connected server,": S + " 笔交易（第一笔是区块 " + S + " 中的 " + S + "）被已连接服务器报告为已确认，",
    "Failed to unsubscribe silent payments for " + S: "取消订阅 " + S + " 的静默支付失败",
    S + S + " shown as unconfirmed until verified.\n\nConsider switching servers, and refreshing the wallet afterwards.": S + S + " 在验证之前显示为未确认。\n\n请考虑切换服务器，然后刷新钱包。",
    S + " confirmation" + S + S: S + " 次确认" + S + S,
    "Unconfirmed " + S + S: "未确认 " + S + S,
    "Slot #" + S: "插槽 #" + S,
    "Discovering... (" + S + "%)": "正在发现...（" + S + "%）",
    "The configured server type is Bitcoin Core, which does not support wallet discovery.\n\nYou can however import the " + S + " and scan the blockchain by supplying a start date.": "配置的服务器类型是 Bitcoin Core，不支持钱包发现。\n\n不过你可以导入 " + S + " 并通过提供开始日期扫描区块链。",
    S + " Error: " + S: S + " 错误：" + S,
    S + " Error": S + " 错误",
    "None of the outputs on this transaction are spendable.\n\nEnsure that the outputs are not frozen" + S: "此交易的所有输出均不可花费。\n\n请确保这些输出未被冻结" + S,
    S + "+ blocks": S + "+ 个区块",
    S + "\nConfirms in: " + S + " (" + S + " from tip)": S + "\n确认于：" + S + "（距顶端 " + S + "）",
    S + "\nFee rate: " + S + " sats/vB": S + "\n手续费率：" + S + " sats/vB",
    S + " the BIP39 passphrase\n" + S: S + " BIP39 密码短语\n" + S,
    "All passphrases create valid wallets.\nThe master fingerprint identifies the keystore and changes as the passphrase changes.\n" + S: "所有密码短语都会创建有效的钱包。\n主指纹标识密钥库，并会随密码短语的变化而改变。\n" + S,
    S + " sats/vB: " + S: S + " sats/vB：" + S,
    "The message in the signed PSBT does not match the message in this dialog.\n\nPSBT message: " + S + "\n\nContinue extracting the signature?": "签名 PSBT 中的消息与此对话框中的消息不匹配。\n\nPSBT 消息：" + S + "\n\n继续提取签名？",
    "The unspent outputs for this private key contain insufficient funds (" + S + " sats) for a transaction at this fee rate.\n\nContinue with a minimum fee rate transaction?": "此私钥的未花费输出资金不足（" + S + " 聪），无法以此手续费率进行交易。\n\n继续使用最低手续费率的交易？",
    "Failed to sign for transaction output " + S + ":" + S: "为交易输出 " + S + " 签名失败：" + S,
    S + " Encoding": S + " 编码",
    "Enter value between " + S + " and " + S + ":": "输入介于 " + S + " 和 " + S + " 之间的值：",
    "Search Wallet " + S: "搜索钱包 " + S,
    "Amount (" + S + ")": "金额（" + S + "）",
    "Spending " + S + " from " + S + " " + S: "花费 " + S + "，来自 " + S + " " + S,
    "Spending " + S + " from" + S: "花费 " + S + "，来自" + S,
    "Input of " + S + "\n" + S + ":" + S + S: "输入 " + S + "\n" + S + "：" + S + S,
    "Change of " + S + " to " + S + "\n" + S + S: "找零 " + S + " 至 " + S + "\n" + S + S,
    "Change of " + S + "\n" + S: "找零 " + S + "\n" + S,
    "Change of " + S + " to " + S: "找零 " + S + " 至 " + S,
    "Toggle Passphrase" + S: "切换密码短语" + S,
    "Reconnect your " + S + " to reset the passphrase.\n\nIf it has a battery, hold down the power button until it restarts.": "重新连接你的 " + S + " 以重置密码短语。\n\n如果它有电池，请按住电源按钮直到它重新启动。",
    "Enter a name for this " + S + ":": "为此 " + S + " 输入名称：",
    S + " Wallet": S + " 钱包",
    "Wallet Password" + S: "钱包密码" + S,
    "BSMS record for keystore " + S + " is not signed, the provided public key cannot be verified as originating from the signer": "密钥库 " + S + " 的 BSMS 记录未签名，无法验证所提供的公钥来自签名者",
    "This file restricts derivation to " + S + ", which is not the standard receive and change derivation. Addresses derived from it would not match those of the other signers in the quorum.": "此文件将派生限制为 " + S + "，这不是标准的接收和找零派生。由此派生的地址与法定人数中其他签名者的地址不匹配。",
    "The first address in this file (" + S + ") is not a valid address: " + S: "此文件中的第一个地址（" + S + "）不是有效地址：" + S,
    "Cannot create card API for " + S: "无法为 " + S + " 创建卡片 API",
    "Import file or QR created by using Advanced/Tools > Export Wallet > Sparrow Wallet" + S + " on your Coldcard. For older firmware use Settings > Multisig Wallets > Export XPUB > " + S + ".": "导入在 Coldcard 上通过 Advanced/Tools > Export Wallet > Sparrow Wallet" + S + " 创建的文件或二维码。旧固件请使用 Settings > Multisig Wallets > Export XPUB > " + S + "。",
    "# " + S + " setup file (created by Sparrow)\n": "# " + S + " 配置文件（由 Sparrow 创建）\n",
    "Import file or QR created by using Advanced/Tools > Export Wallet > Sparrow Wallet" + S + " on your Coldcard. For older firmware use Advanced > MicroSD > Export Wallet > Generic JSON > " + S + ".": "导入在 Coldcard 上通过 Advanced/Tools > Export Wallet > Sparrow Wallet" + S + " 创建的文件或二维码。旧固件请使用 Advanced > MicroSD > Export Wallet > Generic JSON > " + S + "。",
    "Wallet has an incompatible script type of " + S + ", and the correct script type cannot be derived without the master private key.": "钱包的脚本类型 " + S + " 不兼容，没有主私钥无法派生正确的脚本类型。",
    "Select your seed and scan the QR code created by Authenticate > Derive Key > Other Key Derivations > " + S + " > Master Key > Account Descriptor. Click the share icon at the bottom.": "选择你的助记词，并扫描通过 Authenticate > Derive Key > Other Key Derivations > " + S + " > Master Key > Account Descriptor 创建的二维码。点击底部的分享图标。",
    "Enter the code shown on the " + S + ":": "输入 " + S + " 上显示的代码：",
    "Import QR created on your Keycard Shell by selecting Connect software wallet > Bitcoin" + S: "导入在 Keycard Shell 上通过选择 Connect software wallet > Bitcoin" + S + " 创建的二维码",
    " Historical " + S + " values are taken from daily rates and should only be considered as approximate.": " 历史 " + S + " 值取自每日汇率，仅应视为近似值。",
    "Failed to open wallet file.\n" + S: "打开钱包文件失败。\n" + S,
    "Failed to save wallet file.\n" + S: "保存钱包文件失败。\n" + S,
    "Failed to change the password of the wallet file.\n" + S: "更改钱包文件密码失败。\n" + S,
    "Incorrect password for wallet file " + S: "钱包文件 " + S + " 的密码不正确",
    "Failed to open database file.\n" + S: "打开数据库文件失败。\n" + S,
    "Wallet file contains unexpected database routines: " + S + ".": "钱包文件包含意外的数据库例程：" + S + "。",
    "Wallet file contains unexpected database triggers: " + S + ".": "钱包文件包含意外的数据库触发器：" + S + "。",
    "Wallet file contains unexpected check constraints: " + S + ".": "钱包文件包含意外的检查约束：" + S + "。",
    "Wallet file contains unexpected database object types: " + S + ".": "钱包文件包含意外的数据库对象类型：" + S + "。",
    "Wallet file contains unexpected linked tables: " + S + ".": "钱包文件包含意外的链接表：" + S + "。",
    "Wallet file contains unexpected table storage engines: " + S + ".": "钱包文件包含意外的表存储引擎：" + S + "。",
    "Wallet file contains unexpected synonyms: " + S + ".": "钱包文件包含意外的同义词：" + S + "。",
    "Wallet file contains unexpected generated columns: " + S + ".": "钱包文件包含意外的生成列：" + S + "。",
    "Wallet file contains unexpected column default or update expressions: " + S + ".": "钱包文件包含意外的列默认值或更新表达式：" + S + "。",
    "Wallet file contains unexpected database domains: " + S + ".": "钱包文件包含意外的数据库域：" + S + "。",
    "Wallet file contains unexpected database constants: " + S + ".": "钱包文件包含意外的数据库常量：" + S + "。",
    "Wallet file contains unexpected serialized object columns: " + S + ".": "钱包文件包含意外的序列化对象列：" + S + "。",
    "Cannot find transaction output for " + S: "找不到交易输出：" + S,
    S + " cannot sign Taproot transactions": S + " 无法签名 Taproot 交易",
    S + " (with version below v0.14) cannot sign Taproot transactions": S + "（低于 v0.14 的版本）无法签名 Taproot 交易",
    "Error disconnecting Keycard" + S: "断开 Keycard 时出错" + S,
    "Error transmitting Satochip command set" + S: "传输 Satochip 命令集时出错" + S,
    "Error disconnecting Satochip" + S: "断开 Satochip 时出错" + S,
    "Encrypted response has wrong length: " + S: "加密响应长度错误：" + S,
    "Encrypted response has wrong length ciphertext_size: " + S: "加密响应长度错误（ciphertext_size）：" + S,
    S + " / Watch Only Wallet": S + " / 只观察钱包",
    "Could not create ImportPane for importer of type " + S: "无法为此类型的导入器创建导入面板：" + S,
    "Could not authenticate. Server returned " + S: "无法进行身份验证。服务器返回 " + S,
    "Connecting to Bitcoin Core node " + S + "...": "正在连接到 Bitcoin Core 节点 " + S + "...",
    S + " Addresses": S + " 个地址",
    S + " Advanced Settings": S + " 高级设置",
    "Create BIP39 Wallet - " + S: "创建 BIP39 钱包 - " + S,
    "Enter the password for\n" + S: "输入密码\n" + S,
    "The wallet is not valid: " + S: "钱包无效：" + S,
    S + " Receive": S + " 接收",
    S + " Settings": S + " 设置",
    S + " has been successfully added.": S + " 已成功添加。",
    S + " Transactions": S + " 交易",
    S + " UTXOs": S + " 个 UTXO",
    "Create Watch Only Wallet - " + S: "创建只观察钱包 - " + S,
    "Could not determine wallet from descriptor: " + S: "无法从描述符确定钱包：" + S,
    S + " Confirmation": S + " 次确认",
    S + " Confirmations": S + " 次确认",
    "This transaction pays a very high fee rate of " + S + " sats/vB.\n\nBroadcast this transaction?": "此交易支付了非常高的手续费率 " + S + " sats/vB。\n\n广播此交易？",
    "The fee rate for the signed transaction is below the minimum configured relay fee rate for the server of " + S + " sats/vB.": "已签名交易的手续费率低于服务器配置的最低中继手续费率 " + S + " sats/vB。",
    "The fee rate for the signed transaction is below the minimum " + S + " sats/vB. This usually happens because a keystore has created a signature that is larger than necessary.\n\nYou can solve this by recreating the transaction with a slightly increased fee rate.": "已签名交易的手续费率低于最低 " + S + " sats/vB。这通常是因为密钥库创建的签名大于必要大小。\n\n你可以通过略微提高手续费率重新创建交易来解决。",
    "The fee for the transaction was insufficient for relay by your connected server. Increase the fee to at least " + S + " sats to try again.": "交易手续费不足以让已连接服务器中继。将手续费提高到至少 " + S + " 聪以重试。",
    "The fee for the replacement transaction was insufficient. Increase the fee to at least " + S + " sats to try again.": "替换交易的手续费不足。将手续费提高到至少 " + S + " 聪以重试。",
    "The fee rate for the replacement transaction was insufficient. Increase the fee rate to at least " + S + " sats/vB to try again.": "替换交易的手续费率不足。将手续费率提高到至少 " + S + " sats/vB 以重试。",
    S + " from " + S: S + "，来自 " + S,
    "Could not retrieve block transaction for input #" + S: "无法检索输入 #" + S + " 的区块交易",
    S + " - Change": S + " - 找零",
    S + " - Consolidation": S + " - 合并",
    " - Received to " + S: " - 收到至 " + S,
    S + " - Change to " + S: S + " - 找零至 " + S,
    S + " - Payment": S + " - 付款",
    "Show as " + S: "显示为 " + S,
    "Connected Wallet (" + S + ")": "已连接钱包（" + S + "）",
    "Airgapped Wallet (" + S + ")": "气隙钱包（" + S + "）",
    "You are replacing a software wallet with a " + S + ", which will remove the seed. Are you sure?": "你正在用 " + S + " 替换软件钱包，这将删除助记词。确定吗？",
    "QR Code did not contain any information for the " + S + " script type.": "二维码不包含 " + S + " 脚本类型的信息。",
    "QR Code did not contain a valid " + S: "二维码未包含有效的 " + S,
    S + " the following text in a safe place. It contains an encrypted copy of the card's private key, and can be decrypted using the backup key written on the back of the card.": "将以下文本保存在安全的地方：" + S + "。它包含卡片私钥的加密副本，可以使用写在卡片背面的备份密钥解密。",
    "You have entered a " + S + " into a " + S + " wallet. Consider changing the script type to " + S + " to match the default value for a " + S + ".": "你在 " + S + " 钱包中输入了 " + S + "。请考虑将脚本类型更改为 " + S + " 以匹配 " + S + " 的默认值。",
    "To restore this multisig wallet, you need at least " + S + " seeds and ALL of the xpubs! For the xpubs, it is recommended to backup either this wallet file, or the wallet output descriptor.\n\nThe wallet output descriptor contains all " + S + " of the xpubs and is shown below. Alternatively, use the Export button below to export the Sparrow wallet file.": "要恢复此多签钱包，你至少需要 " + S + " 个助记词和所有 xpub！对于 xpub，建议备份此钱包文件或钱包输出描述符。\n\n钱包输出描述符包含所有 " + S + " 个 xpub，如下所示。或者，使用下方的导出按钮导出 Sparrow 钱包文件。",
    "Validation failed for " + S: "验证失败：" + S,
    "The DNS payment instruction for " + S + " resolved correctly but did not contain a bitcoin address.": "针对 " + S + " 的 DNS 支付指令解析正确，但不包含比特币地址。",
    "CPFP (Child Pays For Parent)\n" + S + " sats/vB effective rate": "CPFP（子交易为父交易付费）\n" + S + " sats/vB 有效费率",
    S + " sats/vB (CPFP)": S + " sats/vB（CPFP）",
    " (" + S + " UTXO" + S + " selected)": "（" + S + " 个 UTXO" + S + " 已选择）",
    " (" + S + " UTXO" + S + " excluded)": "（" + S + " 个 UTXO" + S + " 已排除）",
    "Creating tx " + S + ", expecting notifications for \ninputs \n" + S + " and \nchange \n" + S: "正在创建交易 " + S + "，期望收到 \n输入 \n" + S + " 和 \n找零 \n" + S + " 的通知",
    "The notification transaction was successfully sent for payment code " + S + S + ".\n\nYou can send to it by entering the payment code, or selecting `PayNym or Payment code` in the Pay to dropdown.": "通知交易已成功发送，用于支付码 " + S + S + "。\n\n你可以输入支付码，或在“支付给”下拉列表中选择“PayNym 或支付码”向其发送。",
    "Unknown script type of " + S: "未知的脚本类型：" + S,
    "The wallet configuration is specified in the output descriptor.\nChanges to the output descriptor will modify the wallet configuration." + S: "钱包配置由输出描述符指定。\n对输出描述符的更改将修改钱包配置。" + S,
    "The provided output descriptor has " + S + " cosigners, but " + S + " supports a maximum of " + S + ".": "所提供输出描述符有 " + S + " 个共同签名者，但 " + S + " 最多支持 " + S + " 个。",
    "The wallet configuration is specified in the output descriptor.\nThis wallet is no longer editable - create a new wallet to change the descriptor." + S: "钱包配置由输出描述符指定。\n此钱包不再可编辑 - 创建新钱包以更改描述符。" + S,
    "No new accounts with existing transactions were found. " + S: "未找到包含现有交易的新账户。" + S,
    "Wallet loading history for " + S: "钱包正在加载 " + S + " 的历史",
    "Send selected UTXOs. Use " + S + "+click to select multiple.": "发送选中的 UTXO。使用 " + S + "+点击可多选。",
    "Send Selected (" + S + " BTC)": "发送选中的（" + S + " BTC）",
    "Send Selected (" + S + " sats)": "发送选中的（" + S + " sats）",
    "Reopen " + S + "?": "重新打开 " + S + "？",
    "Scanning silent payments... (" + S + "%)": "正在扫描静默支付...（" + S + "%）",
    "Could not determine payment codes for wallet " + S: "无法确定钱包 " + S + " 的支付码",
    "Enter the BIP39 passphrase for keystore:\n" + S: "为密钥库输入 BIP39 密码短语：\n" + S,
    "Master fingerprint: " + S: "主指纹：" + S,
    "Connected at " + S: "已连接到 " + S,
    "Cannot find button for " + S: "找不到按钮：" + S,
    "The URL " + S + " is not valid.": "URL " + S + " 无效。",
    "Fee of " + S + " (" + S + "%)": "手续费 " + S + "（" + S + "%）",
    "1 BTC = " + S + " " + S: "1 BTC = " + S + " " + S,
    "Wallet data is null for " + S: "钱包 " + S + " 的数据为空",
    S + " from " + S: S + "，来自 " + S,
    "Input #" + S + " outpoint txid": "输入 #" + S + " 前向交易点 txid",
    "Input #" + S + " outpoint index": "输入 #" + S + " 前向交易点索引",
    "Input #" + S + " scriptSig length": "输入 #" + S + " scriptSig 长度",
    "Input #" + S + " scriptSig": "输入 #" + S + " scriptSig",
    "Input #" + S + " sequence": "输入 #" + S + " 序号",
    "Input #" + S + " witness count": "输入 #" + S + " 见证数量",
    "Input #" + S + " witness #" + S + " length": "输入 #" + S + " 见证 #" + S + " 长度",
    "Input #" + S + " witness #" + S + " data": "输入 #" + S + " 见证 #" + S + " 数据",
    "Loading wallet, select Transactions tab to view...": "正在加载钱包，选择“交易”标签页以查看...",
    "Cannot find storage for master wallet": "找不到主钱包的存储",
    "Cannot find log file at " + S: "在 " + S + " 找不到日志文件",
    "Check that the correct transaction was signed and exported from the signing device.": "请检查是否从签名设备签名并导出了正确的交易。",
    "Sparrow cannot resolve these outputs to addresses, so they will not appear in the transaction diagram. Review the individual output(s) in the transaction tree carefully before signing or broadcasting.": "Sparrow 无法将这些输出解析为地址，因此它们不会出现在交易图中。请在签名或广播前仔细审阅交易树中的各个输出。",
    "Do you want to try using the existing legacy Bitcoin Core wallet?": "是否尝试使用现有的旧版 Bitcoin Core 钱包？",
    "the descriptors for " + S: S + " 的描述符",
    "Could not delete " + S: "无法删除 " + S,
    "Error fetching transaction " + S: "获取交易 " + S + " 时出错",
    "pay from " + S: "支付自 " + S,
    "Failed to fetch wallet history from " + S + ", reconnecting to another server...": "从 " + S + " 获取钱包历史失败，正在重新连接到另一台服务器...",
    "This means the server is either faulty or dishonest, and what it reported may not have been confirmed at all.": "这意味着服务器要么有故障，要么不诚实，它报告的内容可能根本没有被确认。",
    "A server contradicting itself in this way may be faulty or overloaded, and what it reported cannot be taken as confirmed.": "以这种方式自相矛盾的服务器可能有故障或过载，其报告的内容不能视为已确认。",
    "was reported as confirmed in block " + S: "被报告为已在区块 " + S + " 中确认",
    "by the connected server,": "由已连接服务器，",
    "the first being " + S + " in block " + S: "第一笔是区块 " + S + " 中的 " + S,
    "were reported as confirmed by the connected server,": "被已连接服务器报告为已确认，",
    "Failed to unsubscribe silent payments for " + S: "取消订阅 " + S + " 的静默支付失败",
    "Successfully authenticated to " + S: "已成功验证到 " + S,
    "Failed to authenticate.": "身份验证失败。",
    "Open a ": "打开 ",
    "wallet to ": "钱包以 ",
    "Choose a wallet to ": "选择钱包以 ",
    "and scan the blockchain by supplying a start date.": "并提供开始日期扫描区块链。",
    "Updating to new block height " + S: "正在更新到新区块高度 " + S,
    "reconnecting to another server...": "正在重新连接到另一台服务器...",
    "retrying later": "稍后重试",
    "Connection failed": "连接失败",
    "Do you still want to proceed?": "仍要继续吗？",
    "Trying another server...": "正在尝试另一台服务器...",
    "Sparrow Wallet": "Sparrow Wallet",
    "Requesting PayNym avatar from " + S: "正在从 " + S + " 请求 PayNym 头像",
    "sats) for a transaction at this fee rate.": "聪）无法以此手续费率进行交易。",
    "Continue with a minimum fee rate transaction?": "继续使用最低手续费率的交易？",
    "Error retrieving outputs for address": "检索地址的输出时出错",
    "Use Legacy Encoding (Cobo Vault)": "使用旧版编码（Cobo Vault）",
    "Could not load QR encoding source image for " + S: "无法为 " + S + " 加载二维码编码源图像",
    "EC keys are currently unsupported": "目前不支持 EC 密钥",
    "CryptoOutput did not contain sufficient information": "CryptoOutput 未包含足够的信息",
    "Only indexed derivation path components are supported": "仅支持带索引的派生路径组件",
    "Only extended HD keys are supported in output descriptors": "输出描述符仅支持扩展 HD 密钥",
    "Ignoring invalid QR part " + S: "忽略无效的二维码部分 " + S,
    "Parsed UR of type " + S + " was not a PSBT, transaction or UTF-8 text": "解析的 " + S + " 类型 UR 不是 PSBT、交易或 UTF-8 文本",
    "Unsupported UR type": "不支持的 UR 类型",
    "Unknown UR type of " + S: "未知的 UR 类型：" + S,
    "Unknown script of " + S: "未知的脚本：" + S,
    "Choose a value between " + S + " and " + S: "选择介于 " + S + " 和 " + S + " 之间的值",
    "Fee rate estimate from " + S: "手续费率估算来自 " + S,
    "The following QR contains these seed words. Be careful before displaying or digitally recording it.": "以下二维码包含这些助记词。在显示或数字记录前请小心。",
    "Are you sure you want to continue?": "确定要继续吗？",
    "could not be resolved.": "无法解析。",
    "has no associated address.": "没有关联地址。",
    "No valid recipients were found. Use a CSV file with three columns, and ensure amounts are in " + S + ".": "未找到有效的收款人。请使用三列的 CSV 文件，并确保金额以 " + S + " 为单位。",
    "Send to many recipients by specifying addresses and amounts.": "通过指定地址和金额向多个收款人发送。",
    "Only the first row's label is necessary.": "只有第一行的标签是必需的。",
    "Amount (": "金额（",
    "The first address in this file (" + S + ")": "此文件中的第一个地址（" + S + "）",
    "does not match the first address of the provided descriptor " + S: "与所提供描述符 " + S + " 的第一个地址不匹配",
    "Received from ": "收到来自 ",
    "Received to ": "收到至 ",
    "Change to ": "找零至 ",
    "completed to date": "至今已完成",
    "inputs fetched)": "个输入已获取）",
    "Unknown (": "未知（",
    "Target inclusion within " + S: "目标包含在 " + S,
    "Loading transactions for " + S: "正在加载 " + S + " 的交易",
    "Finding transactions for " + S: "正在查找 " + S + " 的交易",
    "trying another server...": "正在尝试另一台服务器...",
    "Tor running, connecting to " + S + "...": "Tor 正在运行，正在连接到 " + S + "...",
    "Tor failed to start": "Tor 启动失败",
    "Tor failed to start: " + S: "Tor 启动失败：" + S,
    "Cannot broadcast transaction to " + S + " on network " + S: "无法将交易广播到 " + S + "（网络 " + S + "）",
    "Could not connect to Bitcoin Core RPC": "无法连接到 Bitcoin Core RPC",
    "Error retrieving currency rates": "获取汇率时出错",
    "Error retrieving historical currency rates": "获取历史汇率时出错",
    "Requesting exchange rates from " + S: "正在从 " + S + " 获取汇率",
    "Requesting historical exchange rates from " + S: "正在从 " + S + " 获取历史汇率",
    "Failed to retrieve block header for block height " + S: "检索区块高度 " + S + " 的区块头失败",
    "Failed to retrieve block stats for block height " + S: "检索区块高度 " + S + " 的区块统计失败",
    "Cookie file": "Cookie 文件",
    "Server Banner": "服务器横幅",
    "Check if the proxy server is running.": "请检查代理服务器是否正在运行。",
    "Check if Bitcoin Core is running": "请检查 Bitcoin Core 是否正在运行",
    "The connection to the Bitcoin Core node was successful, but it is still syncing and cannot be used yet.": "与 Bitcoin Core 节点的连接成功，但它仍在同步中，尚不能使用。",
    "on protocol version ": "，协议版本 ",
    "Batched RPC enabled.": "已启用批量 RPC。",
    "This may indicate a man-in-the-middle attack!": "这可能表明存在中间人攻击！",
    "This may be simply due to a certificate renewal, or it may indicate a man-in-the-middle attack.": "这可能只是由于证书续期，也可能表明存在中间人攻击。",
    "appears to have changed.": "似乎已更改。",
    "could not be deleted.": "无法删除。",
    "Please delete this file manually.": "请手动删除此文件。",
    "The certificate file at ": "位于 ",
    "The certificate provided by the server at ": "服务器在 ",
    "has expired.": "已过期。",
    "Do you still want to proceed?": "仍要继续吗？",
    "to lockFile at ": "锁定文件位于 ",
    "Change the configured server certificate if you would like to proceed.": "如要继续，请更改配置的服务器证书。",
    "The configured server certificate at ": "在 ",
    "did not match the certificate provided by the server at ": "配置的服务器证书与服务器在 ",
    "Re-entered passphrase did not match": "重新输入的密码短语不一致",
    "Invalid word list - checksum incorrect": "无效的助记词列表 - 校验和错误",
    "Duplicate target blocks": "重复的目标区块",
    "Duplicate dates": "重复的日期",
    "Invalid derivation": "无效的派生路径",
    "Invalid locktime date": "无效的锁定时间日期",
    "Duplicate TXOs": "重复的 TXO",
    "Cannot export wallet with policy type ": "无法导出策略类型为 ",
    "Send Selected (": "发送选中的（",
    "Send Selected (" + S: "发送选中的（" + S,
    "Feerate is higher than the configured maximum. Are you sure you want to proceed?": "手续费率高于配置的最大值。确定要继续吗？",
    "Minimum fee rate is below the configured minimum. Are you sure you want to proceed?": "最低手续费率低于配置的最小值。确定要继续吗？",
    "Send to many": "批量发送",
    "Load CSV": "加载 CSV",
    "CSV file is empty": "CSV 文件为空",
    "Invalid CSV format": "无效的 CSV 格式",
    "Error loading CSV file": "加载 CSV 文件时出错",
}

B2 = {}
for k, v in B.items():
    B2[k.replace(S, "\x01")] = v.replace(S, "\x01")

compared = set()
for line in open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "_work", "compared.txt"), encoding="utf-8"):
    line = line.strip()
    if line.startswith("'") or line.startswith('"'):
        s = line.strip("'\"")
        if s:
            compared.add(s)
drop = [k for k in B2 if k in compared]
print("batch4 keys in compared.txt (dropped):", len(drop))
for k in drop:
    print("  -", repr(k[:60]))
    del B2[k]

json.dump(B2, open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "..", "_work", "java_trans_batch4.json"), "w", encoding="utf-8"), ensure_ascii=True, indent=1)
print("batch4 entries:", len(B2))
